services:
  shelfloom:
    build: .
    ports:
      - "8001:8000"
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./.data:/data
      - ./.data/books:/books
      - /path/to/booklore/books:/source:ro
    restart: unless-stopped
