services:
  shelfloom:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./.data:/data
      - ./.data/books:/books
      - /home/aakash1496/homelab/main-stack/booklore/books:/source:ro
    restart: unless-stopped
