"""add unmatched_sessions table

Revision ID: 1b4a2e8ee126
Revises: 5e6775722915
Create Date: 2026-03-15 13:31:21.821748

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b4a2e8ee126"
down_revision: str | None = "5e6775722915"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unmatched_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("unmatched_entry_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("pages_read", sa.Integer(), nullable=True),
        sa.Column("source_key", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["unmatched_entry_id"], ["unmatched_koreader_entries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("unmatched_sessions")
    # ### end Alembic commands ###
