"""add last_viewed_at to web_serials

Revision ID: 6305b1bb905b
Revises: 7319bc64189e
Create Date: 2026-03-28 05:02:34.009810

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6305b1bb905b"
down_revision: str | None = "7319bc64189e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("web_serials", sa.Column("last_viewed_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("web_serials", "last_viewed_at")
    # ### end Alembic commands ###
